name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}

      - name: Rsync files
        run: |
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --exclude '.git/' \
            --exclude '.github/' \
            ./ numbertarget@merah.cassia.ifost.org.au:/var/www/vhosts/padic.arithmetic.guru/htdocs/
